-- Supabase SQL Editor에서 이 코드를 전체 실행하세요.

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  subject text not null,
  title text not null,
  due date not null,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

-- MVP에서는 로그인 없이 사용할 수 있도록 공개 CRUD를 허용합니다.
-- 개인용/실서비스로 발전시키려면 Supabase Auth + 사용자별 RLS를 추가하세요.

alter table public.tasks enable row level security;

drop policy if exists "Allow public read tasks" on public.tasks;
create policy "Allow public read tasks"
on public.tasks
for select
to anon, authenticated
using (true);

drop policy if exists "Allow public insert tasks" on public.tasks;
create policy "Allow public insert tasks"
on public.tasks
for insert
to anon, authenticated
with check (true);

drop policy if exists "Allow public update tasks" on public.tasks;
create policy "Allow public update tasks"
on public.tasks
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Allow public delete tasks" on public.tasks;
create policy "Allow public delete tasks"
on public.tasks
for delete
to anon, authenticated
using (true);